---
abstract: 'LEGO Indiana Jones theme'
author:
  - 'Chris Williams'
build_requires:
  Test::MetaSyntactic: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MetaSyntactic-legoindianajones
requires:
  Acme::MetaSyntactic::List: 1.001
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/acme-metasyntactic-legoindianajones
  repository: https://github.com/bingos/acme-metasyntactic-legoindianajones.git
version: 0.02
